name: Deploy Next.js (pnpm) to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: video-platform-app
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build Next.js (standalone)
        run: pnpm run build

      - name: Bundle for Azure
        run: |
          rm -rf ./azure
          mkdir -p ./azure/.next
          cp -r ./.next/standalone/* ./azure/
          mkdir -p ./azure/.next/static
          cp -r ./.next/static ./azure/.next/static
          if [ -d "./public" ]; then cp -r ./public ./azure/public; fi
          cp ./package.json ./azure/package.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-azure
          path: azure

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp-spn.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-azure

      # Check if Publish Profile exists
      - name: Deploy with publish profile
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE != '' }}
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      # If Publish Profile is missing, use Service Principal credentials
      - name: Azure login (Service Principal)
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS != '' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Service Principal)
        id: deploy-to-webapp-spn
        if: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE == '' && secrets.AZURE_CREDENTIALS != '' }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .
